### ISSUE TITLE
Question about distutils.errors.CompileError: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by AI-LLM2** [manaai-cn/anchor_computation_tool#2]
我在运行以下命令会出现gcc的问题，使用gcc --version 可以查看到gcc的版本信息；
python anchor_computation_tool/anchor_inspector.py -project_name projects\climb_ladder -dataset_path ./datasets/climb_ladder --annotations True --anchors True --no_gui False

distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "anchor_computation_tool/anchor_inspector.py", line 57, in <module>
    from anchor_utils import draw_annotations, draw_boxes, draw_caption, compute_gt_annotations
  File "/project_code/Train_Code/Yet-Another-EfficientDet-Pytorch01/anchor_computation_tool/anchor_utils.py", line 223, in <module>
    from compute_overlap import compute_overlap
  File "/usr/local/anaconda3/lib/python3.7/site-packages/pyximport/pyximport.py", line 462, in load_module
    language_level=self.language_level)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/pyximport/pyximport.py", line 231, in load_module
    raise exc.with_traceback(tb)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/pyximport/pyximport.py", line 215, in load_module
    inplace=build_inplace, language_level=language_level)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/pyximport/pyximport.py", line 191, in build_module
    reload_support=pyxargs.reload_support)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/pyximport/pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "/usr/local/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/anaconda3/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/local/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/local/anaconda3/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "/usr/local/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/usr/local/anaconda3/lib/python3.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/local/anaconda3/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
ImportError: Building module compute_overlap failed: ["distutils.errors.CompileError: command 'gcc' failed with exit status 1\n"]

**Comment by 17702513221** [comment]
I get this problem too

**Comment by Galaxy-Ding** [comment]
ME TOO

**Comment by Galaxy-Ding** [comment]
Do you any solutions about this problem?
